[package]
name = "clap_host"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
dsp.workspace = true
utils.workspace = true

clack-extensions = { version = "0.1.1", features = [
	"audio-ports",
	"clack-host",
	"gui",
	"latency",
	"log",
	"note-ports",
	"params",
	"preset-discovery",
	"raw-window-handle_06",
	"render",
	"state",
	"state-context",
	"tail",
	"thread-check",
	"thread-pool",
	"timer",
] }
clack-host = "0.1.1"
log = "0.4.33"
raw-window-handle = "0.6.2"
walkdir = "2.5.0"
