[package]
name = "generic_daw_core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
audio_graph.workspace = true
clap_host.workspace = true
dsp.workspace = true
utils.workspace = true

cpal = { version = "0.18.2", features = ["asio", "pipewire"] }
log = "0.4.34"
midir = "0.11.0"
midly = { version = "0.5.3", default-features = false }
oneshot = "0.2.1"
rtrb = "0.4.0"
symphonia = { version = "0.6.1", features = ["all"] }
